### ISSUE TITLE
Formatação

### ISSUE THREAD

**Issue by Rillow** [NicolasMarques/projeto#4]
@NicolasMarques , terminei o PHP, faz o bootstrap pra deixar bonitinho ai ahauhauhah

**Comment by NicolasMarques** [comment]
:+1:

**Comment by Rillow** [comment]
Faltou uma partezinha do php, termina pra mim?

**Comment by NicolasMarques** [comment]
:+1:

**Comment by NicolasMarques** [comment]
Terminei o php e o bootstrap
